### ISSUE TITLE
Compile Error of robotis_op_cpwalk

### ISSUE THREAD

**Issue by huang-CX** [NaoyaSaito/robotis_op_cpwalk#1]
Hi, I have met an error when I compiled the project with catkin_make.  My "cpgen" and "robotis_op_utility" are located in catkin_make/src and "eigen3" is located in /usr/include. The error is showed as follow:

/home/dm/catkin_ws/src/robotis_op_cpwalk/src/test.cpp: In function ‘int main(int, char**)’:
/home/dm/catkin_ws/src/robotis_op_cpwalk/src/test.cpp:127:3: error: ‘Quaternion’ is not a member of ‘cp’
   cp::Quaternion base2r(cp::AngleAxis(cp::deg2rad(90.0), cp::Vector3::UnitX()));
   ^
/home/dm/catkin_ws/src/robotis_op_cpwalk/src/test.cpp:127:3: note: suggested alternatives:
In file included from /usr/include/eigen3/Eigen/Core:296:0,
                 from /usr/local/include/cpgen/eigen_types.h:8,
                 from /usr/local/include/cpgen/com_track.h:7,
                 from /usr/local/include/cpgen/cpgen.h:6,
                 from /home/dm/catkin_ws/src/robotis_op_cpwalk/src/test.cpp:13:
/usr/include/eigen3/Eigen/src/Core/util/ForwardDeclarations.h:270:58: note:   ‘Eigen::Quaternion’
 template<typename Scalar, int Options = AutoAlign> class Quaternion;
                                                          ^
In file included from /home/dm/catkin_ws/src/robotis_op_utility/include/robotis_op_utility/robotis_body.h:4:0,
                 from /home/dm/catkin_ws/src/robotis_op_cpwalk/src/test.cpp:15:
/home/dm/catkin_ws/src/robotis_op_utility/include/robotis_op_utility/eigen_types.h:71:28: note:   ‘robotis::Quaternion’
 typedef Eigen::Quaterniond Quaternion;
                            ^
In file included from /opt/ros/kinetic/include/geometry_msgs/Pose.h:19:0,
                 from /opt/ros/kinetic/include/geometry_msgs/PoseStamped.h:19,
                 from /opt/ros/kinetic/include/moveit/kinematics_base/kinematics_base.h:40,
                 from /opt/ros/kinetic/include/moveit/robot_model/joint_model_group.h:43,
                 from /opt/ros/kinetic/include/moveit/robot_model/robot_model.h:47,
                 from /home/dm/catkin_ws/src/robotis_op_utility/include/robotis_op_utility/robotis_body.h:16,
                 from /home/dm/catkin_ws/src/robotis_op_cpwalk/src/test.cpp:15:
/opt/ros/kinetic/include/geometry_msgs/Quaternion.h:63:61: note:   ‘geometry_msgs::Quaternion’
 typedef ::geometry_msgs::Quaternion_<std::allocator<void> > Quaternion;
                                                             ^
/home/dm/catkin_ws/src/robotis_op_cpwalk/src/test.cpp:128:3: error: ‘Quaternion’ is not a member of ‘cp’
   cp::Quaternion base2l(
   ^
/home/dm/catkin_ws/src/robotis_op_cpwalk/src/test.cpp:128:3: note: suggested alternatives:
In file included from /usr/include/eigen3/Eigen/Core:296:0,
                 from /usr/local/include/cpgen/eigen_types.h:8,
                 from /usr/local/include/cpgen/com_track.h:7,
                 from /usr/local/include/cpgen/cpgen.h:6,
                 from /home/dm/catkin_ws/src/robotis_op_cpwalk/src/test.cpp:13:
/usr/include/eigen3/Eigen/src/Core/util/ForwardDeclarations.h:270:58: note:   ‘Eigen::Quaternion’
 template<typename Scalar, int Options = AutoAlign> class Quaternion;
                                                          ^
In file included from /home/dm/catkin_ws/src/robotis_op_utility/include/robotis_op_utility/robotis_body.h:4:0,
                 from /home/dm/catkin_ws/src/robotis_op_cpwalk/src/test.cpp:15:
/home/dm/catkin_ws/src/robotis_op_utility/include/robotis_op_utility/eigen_types.h:71:28: note:   ‘robotis::Quaternion’
 typedef Eigen::Quaterniond Quaternion;
                            ^
In file included from /opt/ros/kinetic/include/geometry_msgs/Pose.h:19:0,
                 from /opt/ros/kinetic/include/geometry_msgs/PoseStamped.h:19,
                 from /opt/ros/kinetic/include/moveit/kinematics_base/kinematics_base.h:40,
                 from /opt/ros/kinetic/include/moveit/robot_model/joint_model_group.h:43,
                 from /opt/ros/kinetic/include/moveit/robot_model/robot_model.h:47,
                 from /home/dm/catkin_ws/src/robotis_op_utility/include/robotis_op_utility/robotis_body.h:16,
                 from /home/dm/catkin_ws/src/robotis_op_cpwalk/src/test.cpp:15:
/opt/ros/kinetic/include/geometry_msgs/Quaternion.h:63:61: note:   ‘geometry_msgs::Quaternion’
 typedef ::geometry_msgs::Quaternion_<std::allocator<void> > Quaternion;
                                                             ^
/home/dm/catkin_ws/src/robotis_op_cpwalk/src/test.cpp:130:3: error: ‘Quaternion’ is not a member of ‘cp’
   cp::Quaternion base2leg[2] = {base2r, base2l};
   ^
/home/dm/catkin_ws/src/robotis_op_cpwalk/src/test.cpp:130:3: note: suggested alternatives:
In file included from /usr/include/eigen3/Eigen/Core:296:0,
                 from /usr/local/include/cpgen/eigen_types.h:8,
                 from /usr/local/include/cpgen/com_track.h:7,
                 from /usr/local/include/cpgen/cpgen.h:6,
                 from /home/dm/catkin_ws/src/robotis_op_cpwalk/src/test.cpp:13:
/usr/include/eigen3/Eigen/src/Core/util/ForwardDeclarations.h:270:58: note:   ‘Eigen::Quaternion’
 template<typename Scalar, int Options = AutoAlign> class Quaternion;
                                                          ^
In file included from /home/dm/catkin_ws/src/robotis_op_utility/include/robotis_op_utility/robotis_body.h:4:0,
                 from /home/dm/catkin_ws/src/robotis_op_cpwalk/src/test.cpp:15:
/home/dm/catkin_ws/src/robotis_op_utility/include/robotis_op_utility/eigen_types.h:71:28: note:   ‘robotis::Quaternion’
 typedef Eigen::Quaterniond Quaternion;
                            ^
In file included from /opt/ros/kinetic/include/geometry_msgs/Pose.h:19:0,
                 from /opt/ros/kinetic/include/geometry_msgs/PoseStamped.h:19,
                 from /opt/ros/kinetic/include/moveit/kinematics_base/kinematics_base.h:40,
                 from /opt/ros/kinetic/include/moveit/robot_model/joint_model_group.h:43,
                 from /opt/ros/kinetic/include/moveit/robot_model/robot_model.h:47,
                 from /home/dm/catkin_ws/src/robotis_op_utility/include/robotis_op_utility/robotis_body.h:16,
                 from /home/dm/catkin_ws/src/robotis_op_cpwalk/src/test.cpp:15:
/opt/ros/kinetic/include/geometry_msgs/Quaternion.h:63:61: note:   ‘geometry_msgs::Quaternion’
 typedef ::geometry_msgs::Quaternion_<std::allocator<void> > Quaternion;
                                                             ^
/home/dm/catkin_ws/src/robotis_op_cpwalk/src/test.cpp:137:42: error: ‘base2leg’ was not declared in this scope
   cpgen.initialize(wp_com, init_leg_pos, base2leg, end_cp_off, dt, single_sup_time,
                                          ^
/home/dm/catkin_ws/src/robotis_op_cpwalk/src/test.cpp:139:37: error: ‘class cp::cpgen’ has no member named ‘setInitLandPos’
   cp::Pose wp_right_leg_pos = cpgen.setInitLandPos(init_leg_pos[0]);
                                     ^
/home/dm/catkin_ws/src/robotis_op_cpwalk/src/test.cpp:140:36: error: ‘class cp::cpgen’ has no member named ‘setInitLandPos’
   cp::Pose wp_left_leg_pos = cpgen.setInitLandPos(init_leg_pos[1]);
                                    ^
/home/dm/catkin_ws/src/robotis_op_cpwalk/src/test.cpp:143:71: error: no matching function for call to ‘cp::cpgen::getWalkingPattern(cp::Vector3*, cp::Pose*, cp::Pose*)’
   cpgen.getWalkingPattern(&wp_com, &wp_right_leg_pos, &wp_left_leg_pos);
                                                                       ^
In file included from /home/dm/catkin_ws/src/robotis_op_cpwalk/src/test.cpp:13:0:
/usr/local/include/cpgen/cpgen.h:30:8: note: candidate: void cp::cpgen::getWalkingPattern(cp::Vector3*, cp::Quat*, cp::Pose*, cp::Pose*)
   void getWalkingPattern(Vector3* com_pos, Quat* waist_r,
        ^
/usr/local/include/cpgen/cpgen.h:30:8: note:   candidate expects 4 arguments, 3 provided
/home/dm/catkin_ws/src/robotis_op_cpwalk/src/main.cpp: In function ‘int main(int, char**)’:
/home/dm/catkin_ws/src/robotis_op_cpwalk/src/main.cpp:154:3: error: ‘Quaternion’ is not a member of ‘cp’
   cp::Quaternion base2r(cp::AngleAxis(cp::deg2rad(90.0), cp::Vector3::UnitX()));
   ^
/home/dm/catkin_ws/src/robotis_op_cpwalk/src/main.cpp:154:3: note: suggested alternatives:
In file included from /usr/include/eigen3/Eigen/Core:296:0,
                 from /usr/local/include/cpgen/eigen_types.h:8,
                 from /usr/local/include/cpgen/com_track.h:7,
                 from /usr/local/include/cpgen/cpgen.h:6,
                 from /home/dm/catkin_ws/src/robotis_op_cpwalk/src/main.cpp:13:
/usr/include/eigen3/Eigen/src/Core/util/ForwardDeclarations.h:270:58: note:   ‘Eigen::Quaternion’
 template<typename Scalar, int Options = AutoAlign> class Quaternion;
                                                          ^
In file included from /home/dm/catkin_ws/src/robotis_op_utility/include/robotis_op_utility/robotis_body.h:4:0,
                 from /home/dm/catkin_ws/src/robotis_op_cpwalk/src/main.cpp:15:
/home/dm/catkin_ws/src/robotis_op_utility/include/robotis_op_utility/eigen_types.h:71:28: note:   ‘robotis::Quaternion’
 typedef Eigen::Quaterniond Quaternion;
                            ^
In file included from /opt/ros/kinetic/include/geometry_msgs/Pose.h:19:0,
                 from /opt/ros/kinetic/include/geometry_msgs/PoseStamped.h:19,
                 from /opt/ros/kinetic/include/moveit/kinematics_base/kinematics_base.h:40,
                 from /opt/ros/kinetic/include/moveit/robot_model/joint_model_group.h:43,
                 from /opt/ros/kinetic/include/moveit/robot_model/robot_model.h:47,
                 from /home/dm/catkin_ws/src/robotis_op_utility/include/robotis_op_utility/robotis_body.h:16,
                 from /home/dm/catkin_ws/src/robotis_op_cpwalk/src/main.cpp:15:
/opt/ros/kinetic/include/geometry_msgs/Quaternion.h:63:61: note:   ‘geometry_msgs::Quaternion’
 typedef ::geometry_msgs::Quaternion_<std::allocator<void> > Quaternion;
                                                             ^
/home/dm/catkin_ws/src/robotis_op_cpwalk/src/main.cpp:155:3: error: ‘Quaternion’ is not a member of ‘cp’
   cp::Quaternion base2l(
   ^
/home/dm/catkin_ws/src/robotis_op_cpwalk/src/main.cpp:155:3: note: suggested alternatives:
In file included from /usr/include/eigen3/Eigen/Core:296:0,
                 from /usr/local/include/cpgen/eigen_types.h:8,
                 from /usr/local/include/cpgen/com_track.h:7,
                 from /usr/local/include/cpgen/cpgen.h:6,
                 from /home/dm/catkin_ws/src/robotis_op_cpwalk/src/main.cpp:13:
/usr/include/eigen3/Eigen/src/Core/util/ForwardDeclarations.h:270:58: note:   ‘Eigen::Quaternion’
 template<typename Scalar, int Options = AutoAlign> class Quaternion;
                                                          ^
In file included from /home/dm/catkin_ws/src/robotis_op_utility/include/robotis_op_utility/robotis_body.h:4:0,
                 from /home/dm/catkin_ws/src/robotis_op_cpwalk/src/main.cpp:15:
/home/dm/catkin_ws/src/robotis_op_utility/include/robotis_op_utility/eigen_types.h:71:28: note:   ‘robotis::Quaternion’
 typedef Eigen::Quaterniond Quaternion;
                            ^
In file included from /opt/ros/kinetic/include/geometry_msgs/Pose.h:19:0,
                 from /opt/ros/kinetic/include/geometry_msgs/PoseStamped.h:19,
                 from /opt/ros/kinetic/include/moveit/kinematics_base/kinematics_base.h:40,
                 from /opt/ros/kinetic/include/moveit/robot_model/joint_model_group.h:43,
                 from /opt/ros/kinetic/include/moveit/robot_model/robot_model.h:47,
                 from /home/dm/catkin_ws/src/robotis_op_utility/include/robotis_op_utility/robotis_body.h:16,
                 from /home/dm/catkin_ws/src/robotis_op_cpwalk/src/main.cpp:15:
/opt/ros/kinetic/include/geometry_msgs/Quaternion.h:63:61: note:   ‘geometry_msgs::Quaternion’
 typedef ::geometry_msgs::Quaternion_<std::allocator<void> > Quaternion;
                                                             ^
/home/dm/catkin_ws/src/robotis_op_cpwalk/src/main.cpp:157:3: error: ‘Quaternion’ is not a member of ‘cp’
   cp::Quaternion base2leg[2] = {base2r, base2l};
   ^
/home/dm/catkin_ws/src/robotis_op_cpwalk/src/main.cpp:157:3: note: suggested alternatives:
In file included from /usr/include/eigen3/Eigen/Core:296:0,
                 from /usr/local/include/cpgen/eigen_types.h:8,
                 from /usr/local/include/cpgen/com_track.h:7,
                 from /usr/local/include/cpgen/cpgen.h:6,
                 from /home/dm/catkin_ws/src/robotis_op_cpwalk/src/main.cpp:13:
/usr/include/eigen3/Eigen/src/Core/util/ForwardDeclarations.h:270:58: note:   ‘Eigen::Quaternion’
 template<typename Scalar, int Options = AutoAlign> class Quaternion;
                                                          ^
In file included from /home/dm/catkin_ws/src/robotis_op_utility/include/robotis_op_utility/robotis_body.h:4:0,
                 from /home/dm/catkin_ws/src/robotis_op_cpwalk/src/main.cpp:15:
/home/dm/catkin_ws/src/robotis_op_utility/include/robotis_op_utility/eigen_types.h:71:28: note:   ‘robotis::Quaternion’
 typedef Eigen::Quaterniond Quaternion;
                            ^
In file included from /opt/ros/kinetic/include/geometry_msgs/Pose.h:19:0,
                 from /opt/ros/kinetic/include/geometry_msgs/PoseStamped.h:19,
                 from /opt/ros/kinetic/include/moveit/kinematics_base/kinematics_base.h:40,
                 from /opt/ros/kinetic/include/moveit/robot_model/joint_model_group.h:43,
                 from /opt/ros/kinetic/include/moveit/robot_model/robot_model.h:47,
                 from /home/dm/catkin_ws/src/robotis_op_utility/include/robotis_op_utility/robotis_body.h:16,
                 from /home/dm/catkin_ws/src/robotis_op_cpwalk/src/main.cpp:15:
/opt/ros/kinetic/include/geometry_msgs/Quaternion.h:63:61: note:   ‘geometry_msgs::Quaternion’
 typedef ::geometry_msgs::Quaternion_<std::allocator<void> > Quaternion;
                                                             ^
/home/dm/catkin_ws/src/robotis_op_cpwalk/src/main.cpp:167:42: error: ‘base2leg’ was not declared in this scope
   cpgen.initialize(wp_com, init_leg_pos, base2leg, end_cp_off, dt, single_sup_time,
                                          ^
/home/dm/catkin_ws/src/robotis_op_cpwalk/src/main.cpp:169:37: error: ‘class cp::cpgen’ has no member named ‘setInitLandPos’
   cp::Pose wp_right_leg_pos = cpgen.setInitLandPos(init_leg_pos[0]);
                                     ^
/home/dm/catkin_ws/src/robotis_op_cpwalk/src/main.cpp:170:36: error: ‘class cp::cpgen’ has no member named ‘setInitLandPos’
   cp::Pose wp_left_leg_pos = cpgen.setInitLandPos(init_leg_pos[1]);
                                    ^
/home/dm/catkin_ws/src/robotis_op_cpwalk/src/main.cpp:205:73: error: no matching function for call to ‘cp::cpgen::getWalkingPattern(cp::Vector3*, cp::Pose*, cp::Pose*)’
     cpgen.getWalkingPattern(&wp_com, &wp_right_leg_pos, &wp_left_leg_pos);
                                                                         ^
In file included from /home/dm/catkin_ws/src/robotis_op_cpwalk/src/main.cpp:13:0:
/usr/local/include/cpgen/cpgen.h:30:8: note: candidate: void cp::cpgen::getWalkingPattern(cp::Vector3*, cp::Quat*, cp::Pose*, cp::Pose*)
   void getWalkingPattern(Vector3* com_pos, Quat* waist_r,
        ^
/usr/local/include/cpgen/cpgen.h:30:8: note:   candidate expects 4 arguments, 3 provided
/home/dm/catkin_ws/src/robotis_op_cpwalk/src/main.cpp:209:32: error: ‘class cp::cpgen’ has no member named ‘getEndCP’
     cp::Vector2 end_cp = cpgen.getEndCP();
                                ^
robotis_op_cpwalk/CMakeFiles/test_robotis_op_cpwalk.dir/build.make:62: recipe for target 'robotis_op_cpwalk/CMakeFiles/test_robotis_op_cpwalk.dir/src/test.cpp.o' failed
make[2]: *** [robotis_op_cpwalk/CMakeFiles/test_robotis_op_cpwalk.dir/src/test.cpp.o] Error 1
CMakeFiles/Makefile2:13735: recipe for target 'robotis_op_cpwalk/CMakeFiles/test_robotis_op_cpwalk.dir/all' failed
make[1]: *** [robotis_op_cpwalk/CMakeFiles/test_robotis_op_cpwalk.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
robotis_op_cpwalk/CMakeFiles/robotis_op_cpwalk_node.dir/build.make:62: recipe for target 'robotis_op_cpwalk/CMakeFiles/robotis_op_cpwalk_node.dir/src/main.cpp.o' failed
make[2]: *** [robotis_op_cpwalk/CMakeFiles/robotis_op_cpwalk_node.dir/src/main.cpp.o] Error 1
CMakeFiles/Makefile2:13698: recipe for target 'robotis_op_cpwalk/CMakeFiles/robotis_op_cpwalk_node.dir/all' failed
make[1]: *** [robotis_op_cpwalk/CMakeFiles/robotis_op_cpwalk_node.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j8 -l8" failed

**Comment by s-naoya** [comment]
"robotis_op_cpwalk" is a ROS library, but "cpgen" is not a ROS library.
Before catkin_make "robotis_op_cpwalk", "cpgen" to a suitable folder and make it with the following command.
```
git clone git@github.com:s-naoya/cpgen.git
cd cpgen
cmake .
make
sudo make install
```
Thank you!

**Comment by huang-CX** [comment]
Thank you for your answer. But which folder is suitable to locate the "cpgen".

Thanks again!

**Comment by s-naoya** [comment]
It is suitable for most folders below the home folder, but catkin_ws should be avoided.
e.g.
```
cd ~
mkdir works && cd works
git clone git@github.com:s-naoya/cpgen.git
cd cpgen
cmake .
make
sudo make install
```

**Comment by huang-CX** [comment]
I have successfully compiled "cpgen", but I still get the same error when compiling "robotis_op_cpwalk" through catkin_make.

**Comment by s-naoya** [comment]
We have found the cause of the problem.
Due to complications, the version of cpgen used in this robotis_op_cpwalk is not public, so there are some discrepancies.
This may be resolved if you revert to committing robotis_op_cpwalk.
Also, this repository is not currently maintained.
Sorry...
